apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alexellis-fn-secrets
  namespace: openfaas-fn
spec:
  encryptedData:
    incoming-webhook-url: AgCZ3ArJehn9VVY2wwiAOqZE56yc84zW9a3dsdZQizM6AHc4LHBkaxte7R0wwxc/wWJK5ar38HmSa7pRXiO6bZ8ydHRGQAtDwt0TpqKss+kSunU+OWFMt0y28e24L5sZAsjTKUd/kMNs2m9AtRD8rYHffoDZBD3kNSutOUL/Tagg24AVCGA/mmqVdMkpfHK6yyl53zdKhthcSJ7TNReZ+D/yxS8nbRUQsnKFjBeOxtPx845P9tLtDkodZzPM7HubnCBfXtj/inp5UvAowAWgfDL+qE9flbZM34hUgON4Uc4YVbNPS2w9AEW4XApzX7LMwWw0bC91wvHjN8nX1KQYuLalNyEi7kFgpA/IZ+zpnP8QYPhgyid7jawVNL007y15cyfsMZtAdD7ivcPtBQ8mwgjGG7lvOHftTV7jCLtMjZu534nnwQhVoWZjMy+LC4NPqJaQkwW9dXZIbdBV0/9pwUqNwv9kGdR15wKuJTw5/MJyAJjZFTP8nLNwQP5soy/+SLhlJLd8HhfTi8FbT/kC6YB8oijbv57nxeygpJSDGxxl8fU/0+HaZ+BH4Xvvr2yg3Dt3A82JGGE4HZMoAMSvE+ueFGstlSd6EAaIwfOXEXimbMstC6WU9r4uHa2yliMEhQuBGQpCfvnQeCarojOsOg3m0TTm102CODWMpOhtXM83wUkWZEs/HG1UxcBi9BXC2wT703tMViJnCtIKAA/D5nZDMp2XK0T3H43llmg=
  template:
    metadata:
      creationTimestamp: null
      name: alexellis-fn-secrets
      namespace: openfaas-fn
status: {}

