version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  has-secret:
    lang: python3
    handler: ./has-secret
    image: has-secret:latest
    secrets:
    - fn-secrets

